"""add_auth_header_scheme_to_agent_credentials

Revision ID: 7c0429218ebd
Revises: 8bb510355248
Create Date: 2026-03-12 11:09:14.512642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0429218ebd'
down_revision: Union[str, Sequence[str], None] = '8bb510355248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_credentials', sa.Column('auth_header', sa.String(), nullable=True))
    op.add_column('agent_credentials', sa.Column('auth_scheme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_credentials', 'auth_scheme')
    op.drop_column('agent_credentials', 'auth_header')
    # ### end Alembic commands ###
