"""add_agent_credentials

Revision ID: 8bb510355248
Revises: 3e75d3535bb3
Create Date: 2026-03-12 10:51:48.252682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb510355248'
down_revision: Union[str, Sequence[str], None] = '3e75d3535bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_credentials',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.String(), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_credentials_agent_id', 'agent_credentials', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_credentials_agent_id', table_name='agent_credentials')
    op.drop_table('agent_credentials')
    # ### end Alembic commands ###
