"""add_missing_tables

Revision ID: 8848633307e2
Revises: f5f2658b44aa
Create Date: 2026-03-26 00:09:05.296614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8848633307e2'
down_revision: Union[str, Sequence[str], None] = 'f5f2658b44aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('written_by', sa.UUID(), nullable=True),
    sa.Column('written_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_entries_context_id'), 'context_entries', ['context_id'], unique=False)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('definition', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('triggers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('recovery', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_name'), 'workflow_definitions', ['name'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='execution_status'), nullable=False),
    sa.Column('trigger_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('parent_execution_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_parent_execution_id'), 'workflow_executions', ['parent_execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('process_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('agent', 'skill', 'condition', 'sub_workflow', 'plan', name='step_type'), nullable=False),
    sa.Column('target_id', sa.String(length=512), nullable=True),
    sa.Column('target_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='process_status'), nullable=False),
    sa.Column('input', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_entries_execution_id'), 'process_entries', ['execution_id'], unique=False)
    op.create_table('orders',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('capability', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('tick', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('wallet_type', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND agent_id IS NULL) OR (user_id IS NULL AND agent_id IS NOT NULL)', name='ck_wallets_one_owner'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_wallets_agent_id', 'wallets', ['agent_id'], unique=True, postgresql_where=sa.text('agent_id IS NOT NULL'))
    op.create_index('uq_wallets_user_id', 'wallets', ['user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('credit_purchases',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.String(length=50), nullable=False),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('bid_order_id', sa.UUID(), nullable=False),
    sa.Column('ask_order_id', sa.UUID(), nullable=False),
    sa.Column('buyer_agent_id', sa.UUID(), nullable=False),
    sa.Column('seller_agent_id', sa.UUID(), nullable=False),
    sa.Column('capability', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='settled', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tick', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ask_order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bid_order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('pricing_strategy', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('base_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'base_price')
    op.drop_column('agents', 'pricing_strategy')
    op.drop_table('transactions')
    op.drop_table('trades')
    op.drop_table('credit_purchases')
    op.drop_index('uq_wallets_user_id', table_name='wallets', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_wallets_agent_id', table_name='wallets', postgresql_where=sa.text('agent_id IS NOT NULL'))
    op.drop_table('wallets')
    op.drop_table('orders')
    op.drop_index(op.f('ix_process_entries_execution_id'), table_name='process_entries')
    op.drop_table('process_entries')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_parent_execution_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_workflow_definitions_name'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_context_entries_context_id'), table_name='context_entries')
    op.drop_table('context_entries')
    # ### end Alembic commands ###
