"""make invocation_logs target_agent_id nullable

Revision ID: 82c36691dae3
Revises: add_pricing_enabled
Create Date: 2026-03-26 01:58:10.344452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c36691dae3'
down_revision: Union[str, Sequence[str], None] = 'add_pricing_enabled'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invocation_logs', 'target_agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('invocation_logs_target_agent_id_fkey'), 'invocation_logs', type_='foreignkey')
    op.create_foreign_key(None, 'invocation_logs', 'agents', ['target_agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invocation_logs', type_='foreignkey')
    op.create_foreign_key(op.f('invocation_logs_target_agent_id_fkey'), 'invocation_logs', 'agents', ['target_agent_id'], ['id'])
    op.alter_column('invocation_logs', 'target_agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
